"""fase_9_cross_border_margins

Revision ID: 0b94d6f23876
Revises: c495f97b7d01
Create Date: 2026-08-12 13:32:10.408959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b94d6f23876'
down_revision: Union[str, Sequence[str], None] = 'c495f97b7d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('cross_border_margin', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('cross_border_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_listings_cross_border_margin'), 'listings', ['cross_border_margin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_cross_border_margin'), table_name='listings')
    op.drop_column('listings', 'cross_border_score')
    op.drop_column('listings', 'cross_border_margin')
    # ### end Alembic commands ###
