"""Fase 5: tabla vehicle_matches (traza de matching)

Revision ID: 31004be0da9c
Revises: c1f3a5b7c9d1
Create Date: 2026-08-11 23:34:24.620894

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31004be0da9c'
down_revision: str | Sequence[str] | None = 'c1f3a5b7c9d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_matches_listing_id'), 'vehicle_matches', ['listing_id'], unique=True)
    op.create_index(op.f('ix_vehicle_matches_vehicle_id'), 'vehicle_matches', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_matches_vehicle_id'), table_name='vehicle_matches')
    op.drop_index(op.f('ix_vehicle_matches_listing_id'), table_name='vehicle_matches')
    op.drop_table('vehicle_matches')
    # ### end Alembic commands ###
