"""fase_2_is_historical_en_listings

Revision ID: 53d05b4fbb83
Revises: 31004be0da9c
Create Date: 2026-08-12 08:54:20.351571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d05b4fbb83'
down_revision: Union[str, Sequence[str], None] = '31004be0da9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('is_historical', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_listings_is_historical'), 'listings', ['is_historical'], unique=False)
    # ### end Alembic commands ###

    # Data migration: los listings de mobile.de existentes provienen todos de
    # Wayback Machine (el live está bloqueado), así que son datos históricos y
    # no deben aparecer en el panel de anuncios activos.
    listings = sa.table('listings', sa.column('is_historical', sa.Boolean()))
    op.execute(listings.update().where(sa.text("source = 'mobile_de'")).values(is_historical=True))


def downgrade() -> None:
    """Downgrade schema."""
    listings = sa.table('listings', sa.column('is_historical', sa.Boolean()))
    op.execute(listings.update().where(sa.text("source = 'mobile_de'")).values(is_historical=False))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_is_historical'), table_name='listings')
    op.drop_column('listings', 'is_historical')
    # ### end Alembic commands ###
