"""dual market valuation es price

Revision ID: 8dbcaea7206d
Revises: fb18ba32befd
Create Date: 2026-08-13 08:59:43.950042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbcaea7206d'
down_revision: Union[str, Sequence[str], None] = 'fb18ba32befd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('predicted_price_es', sa.Float(), nullable=True))
    op.create_index(op.f('ix_listings_predicted_price_es'), 'listings', ['predicted_price_es'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_predicted_price_es'), table_name='listings')
    op.drop_column('listings', 'predicted_price_es')
    # ### end Alembic commands ###
