"""fase_6_bargain_score_en_listings

Revision ID: b1e576fc7111
Revises: 53d05b4fbb83
Create Date: 2026-08-12 11:12:53.805570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e576fc7111'
down_revision: Union[str, Sequence[str], None] = '53d05b4fbb83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('bargain_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_listings_bargain_score'), 'listings', ['bargain_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_bargain_score'), table_name='listings')
    op.drop_column('listings', 'bargain_score')
    # ### end Alembic commands ###
