"""fase_6_margen_absoluto_y_predicted_price

Revision ID: c495f97b7d01
Revises: d15e9a2d6795
Create Date: 2026-08-12 12:48:20.276015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c495f97b7d01'
down_revision: Union[str, Sequence[str], None] = 'd15e9a2d6795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('absolute_margin', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('predicted_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'predicted_price')
    op.drop_column('listings', 'absolute_margin')
    # ### end Alembic commands ###
