"""fase_7_import_costs_en_listings

Revision ID: d15e9a2d6795
Revises: b1e576fc7111
Create Date: 2026-08-12 12:18:34.079138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15e9a2d6795'
down_revision: Union[str, Sequence[str], None] = 'b1e576fc7111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('estimated_import_cost', sa.Float(), nullable=True))
    op.add_column('listings', sa.Column('total_cost_es', sa.Float(), nullable=True))
    op.create_index(op.f('ix_listings_total_cost_es'), 'listings', ['total_cost_es'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_total_cost_es'), table_name='listings')
    op.drop_column('listings', 'total_cost_es')
    op.drop_column('listings', 'estimated_import_cost')
    # ### end Alembic commands ###
