"""fase_10_alertas_y_notificaciones

Revision ID: fb18ba32befd
Revises: 0b94d6f23876
Create Date: 2026-08-12 17:06:41.410569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb18ba32befd'
down_revision: Union[str, Sequence[str], None] = '0b94d6f23876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_key', sa.String(length=64), nullable=False),
    sa.Column('max_purchase_price', sa.Float(), nullable=True),
    sa.Column('max_total_cost', sa.Float(), nullable=True),
    sa.Column('min_profit', sa.Float(), nullable=True),
    sa.Column('min_roi', sa.Float(), nullable=True),
    sa.Column('min_bargain_score', sa.Float(), nullable=True),
    sa.Column('max_risk_score', sa.Float(), nullable=True),
    sa.Column('brands', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fuel', sa.String(length=30), nullable=True),
    sa.Column('transmission', sa.String(length=30), nullable=True),
    sa.Column('max_mileage', sa.Integer(), nullable=True),
    sa.Column('year_min', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('notify_web', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_email', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_key')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preference_id'], ['alert_preferences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_listing_id'), 'notifications', ['listing_id'], unique=False)
    op.create_index(op.f('ix_notifications_preference_id'), 'notifications', ['preference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_preference_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_listing_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('alert_preferences')
    # ### end Alembic commands ###
